name = input("Enter Your Name: ")
age = input("Enter Your Age: ")
cgpa = input("Enter Your CGPA: ")
print("\n")
print("Student Information")
print("--------------------")
print("Name : "+name)
print("Age : " +age)
print ("CGPA : "+cgpa)